cd xmls
curl https://codes.sikb.nl/0101/IMMetingen/Bemonsteringsapparaat.xml -o Bemonsteringsapparaat.xml
curl https://codes.sikb.nl/0101/IMMetingen/Bemonsteringsmethode.xml -o Bemonsteringsmethode.xml
curl https://codes.sikb.nl/0101/IMMetingen/Bemonsteringssoort.xml -o Bemonsteringssoort.xml
curl https://codes.sikb.nl/0101/IMMetingen/BiologischKenmerk.xml -o BiologischKenmerk.xml
curl https://codes.sikb.nl/0101/IMMetingen/Biotaxon.xml -o Biotaxon.xml
curl https://codes.sikb.nl/0101/IMMetingen/BodemlaagBodemkenmerken.xml -o BodemlaagBodemkenmerken.xml
curl https://codes.sikb.nl/0101/IMMetingen/BodemlaagBodemkenmerkenGradatie.xml -o BodemlaagBodemkenmerkenGradatie.xml
curl https://codes.sikb.nl/0101/IMMetingen/BodemlaagBodemkenmerkenOorsprong.xml -o BodemlaagBodemkenmerkenOorsprong.xml
curl https://codes.sikb.nl/0101/IMMetingen/BodemlaagBodemkenmerkenSpecificatie.xml -o BodemlaagBodemkenmerkenSpecificatie.xml
curl https://codes.sikb.nl/0101/IMMetingen/BodemlaagType.xml -o BodemlaagType.xml
curl https://codes.sikb.nl/0101/IMMetingen/Bodemsoort.xml -o Bodemsoort.xml
curl https://codes.sikb.nl/0101/IMMetingen/BodemsoortMediaan.xml -o BodemsoortMediaan.xml
curl https://codes.sikb.nl/0101/IMMetingen/CertificeringsCode.xml -o CertificeringsCode.xml
curl https://codes.sikb.nl/0101/IMMetingen/Compartiment.xml -o Compartiment.xml
curl https://codes.sikb.nl/0101/IMMetingen/Eenheid.xml -o Eenheid.xml
curl https://codes.sikb.nl/0101/IMMetingen/Geslacht.xml -o Geslacht.xml
curl https://codes.sikb.nl/0101/IMMetingen/GrindGehalte.xml -o GrindGehalte.xml
curl https://codes.sikb.nl/0101/IMMetingen/Hoedanigheid.xml -o Hoedanigheid.xml
curl https://codes.sikb.nl/0101/IMMetingen/Juistheidsoordeel.xml -o Juistheidsoordeel.xml
curl https://codes.sikb.nl/0101/IMMetingen/JuistheidsoordeelProcedure.xml -o JuistheidsoordeelProcedure.xml
curl https://codes.sikb.nl/0101/IMMetingen/J_of_N.xml -o J_of_N.xml
curl https://codes.sikb.nl/0101/IMMetingen/Kansverdeling.xml -o Kansverdeling.xml
curl https://codes.sikb.nl/0101/IMMetingen/KenmerkBodemlaag.xml -o KenmerkBodemlaag.xml
curl https://codes.sikb.nl/0101/IMMetingen/KenmerkMonstername.xml -o KenmerkMonstername.xml
curl https://codes.sikb.nl/0101/IMMetingen/Kleur.xml -o Kleur.xml
curl https://codes.sikb.nl/0101/IMMetingen/Kleursterkte.xml -o Kleursterkte.xml
curl https://codes.sikb.nl/0101/IMMetingen/Kwaliteitsoordeel.xml -o Kwaliteitsoordeel.xml
curl https://codes.sikb.nl/0101/IMMetingen/LabopdrachtStatus.xml -o LabopdrachtStatus.xml
curl https://codes.sikb.nl/0101/IMMetingen/LocatieTypeWaardebepaling.xml -o LocatieTypeWaardebepaling.xml
curl https://codes.sikb.nl/0101/IMMetingen/MateriaalMonsterVerpakking.xml -o MateriaalMonsterVerpakking.xml
curl https://codes.sikb.nl/0101/IMMetingen/Meetapparaat.xml -o Meetapparaat.xml
curl https://codes.sikb.nl/0101/IMMetingen/Meetinstantie.xml -o Meetinstantie.xml
curl https://codes.sikb.nl/0101/IMMetingen/MeetObjectSoort.xml -o MeetObjectSoort.xml
curl https://codes.sikb.nl/0101/IMMetingen/Monsterbewerkingsmethode.xml -o Monsterbewerkingsmethode.xml
curl https://codes.sikb.nl/0101/IMMetingen/MonsterType.xml -o MonsterType.xml
curl https://codes.sikb.nl/0101/IMMetingen/MonsterVerpakking.xml -o MonsterVerpakking.xml
curl https://codes.sikb.nl/0101/IMMetingen/MonsterVoorbehandeling.xml -o MonsterVoorbehandeling.xml
curl https://codes.sikb.nl/0101/IMMetingen/OliewaterReactieMate.xml -o OliewaterReactieMate.xml
curl https://codes.sikb.nl/0101/IMMetingen/Onderzoekssoort.xml -o Onderzoekssoort.xml
curl https://codes.sikb.nl/0101/IMMetingen/Orgaan.xml -o Orgaan.xml
curl https://codes.sikb.nl/0101/IMMetingen/OrganischeStofGehalte.xml -o OrganischeStofGehalte.xml
curl https://codes.sikb.nl/0101/IMMetingen/Parameter.xml -o Parameter.xml
curl https://codes.sikb.nl/0101/IMMetingen/RelatedObservationRollen.xml -o RelatedObservationRollen.xml
curl https://codes.sikb.nl/0101/IMMetingen/RelatedSamplingFeatureRollen.xml -o RelatedSamplingFeatureRollen.xml
curl https://codes.sikb.nl/0101/IMMetingen/RelatedSubjectRollen.xml -o RelatedSubjectRollen.xml
curl https://codes.sikb.nl/0101/IMMetingen/RolBetrokkene.xml -o RolBetrokkene.xml
curl https://codes.sikb.nl/0101/IMMetingen/Staat.xml -o Staat.xml
curl https://codes.sikb.nl/0101/IMMetingen/StatistischeParameter.xml -o StatistischeParameter.xml
curl https://codes.sikb.nl/0101/IMMetingen/ValidationScore.xml -o ValidationScore.xml
curl https://codes.sikb.nl/0101/IMMetingen/ValidationSteps.xml -o ValidationSteps.xml
curl https://codes.sikb.nl/0101/IMMetingen/Waardebepalingsmethode.xml -o Waardebepalingsmethode.xml
curl https://codes.sikb.nl/0101/IMMetingen/Waardebepalingstechniek.xml -o Waardebepalingstechniek.xml
curl https://codes.sikb.nl/0101/IMMetingen/Waardebewerkingsmethode.xml -o Waardebewerkingsmethode.xml
curl https://codes.sikb.nl/0101/IMMetingen/WaarnemingReeksType.xml -o WaarnemingReeksType.xml