cd xmls
curl https://codes.sikb.nl/0101/IMSIKB0101/aanleiding.xml -o aanleiding.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/Aanvulling.xml -o Aanvulling.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/Afdichting.xml -o Afdichting.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/Afwerking.xml -o Afwerking.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/AfwerkingType.xml -o AfwerkingType.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/Applicaties.xml -o Applicaties.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/asbestaanwezigheid.xml -o asbestaanwezigheid.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/asbesthoudendmateriaal.xml -o asbesthoudendmateriaal.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/asbest_status.xml -o asbest_status.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/bedrijvenregelingstatus.xml -o bedrijvenregelingstatus.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/benoemd.xml -o benoemd.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/besluit.xml -o besluit.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/besl_stat.xml -o besl_stat.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/bestemming.xml -o bestemming.xml
curl https://codes.sikb.nl/0101/12.1.0/IMSIKB0101/Betrokkenen.xml -o betrokkenen.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/bodemfunctieklasse.xml -o bodemfunctieklasse.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/bodemkwaliteitsklasse.xml -o bodemkwaliteitsklasse.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/bouwstof.xml -o bouwstof.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/Bronhouders.xml -o Bronhouders.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/conserveringsmiddel.xml -o conserveringsmiddel.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/contourType.xml -o contourType.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/convenant.xml -o convenant.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/convenantpartij.xml -o convenantpartij.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/criterium_risico.xml -o criterium_risico.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/database.xml -o database.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/eut_status.xml -o eut_status.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/fase.xml -o fase.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/functie.xml -o functie.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/gebruik.xml -o gebruik.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/gebruiksbeperking.xml -o gebruiksbeperking.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/gradatie.xml -o gradatie.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/grondbewerkingsinrichting.xml -o grondbewerkingsinrichting.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/hbb_soort_bedrijf.xml -o hbb_soort_bedrijf.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/hechtgebondenheid.xml -o hechtgebondenheid.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/initiatief.xml -o initiatief.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/kadastrale_gemeentecode.xml -o kadastrale_gemeentecode.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/knelpunt_aanpak_risico.xml -o knelpunt_aanpak_risico.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/kostenindeling.xml -o kostenindeling.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/kostenstatus.xml -o kostenstatus.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/kostenverdeling.xml -o kostenverdeling.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/kostenverdeling_seb.xml -o kostenverdeling_seb.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/kwalificatie.xml -o kwalificatie.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/landwater.xml -o landwater.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/layer.xml -o layer.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/lettercode_bevoegd_gezag.xml -o lettercode_bevoegd_gezag.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/Leveranciers.xml -o Leveranciers.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/MaaiveldType.xml -o MaaiveldType.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/materiaal.xml -o materiaal.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/melding.xml -o melding.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/nazorgkader.xml -o nazorgkader.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/NormClassificatie.xml -o NormClassificatie.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/ondstatbsl.xml -o ondstatbsl.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/ond_type.xml -o ond_type.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/overschrijding.xml -o overschrijding.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/PrijsafspraakType.xml -o PrijsafspraakType.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/ReinigingsType.xml -o ReinigingsType.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/risico.xml -o risico.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/sanering.xml -o sanering.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/saneringsaanleiding.xml -o saneringsaanleiding.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/saneringscriterium.xml -o saneringscriterium.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/san_bovengrond.xml -o san_bovengrond.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/san_ondergrond.xml -o san_ondergrond.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/segment.xml -o segment.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/Situatiebeschrijving.xml -o Situatiebeschrijving.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/soort_bevoegd_gezag.xml -o soort_bevoegd_gezag.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/soort_bijlage.xml -o soort_bijlage.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/soort_melding.xml -o soort_melding.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/soort_toepassing.xml -o soort_toepassing.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/soort_verklaring.xml -o soort_verklaring.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/specificatie_gbt.xml -o specificatie_gbt.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/spoedveroorzakend.xml -o spoedveroorzakend.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/status_oord.xml -o status_oord.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/status_ver.xml -o status_ver.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/stat_dyn.xml -o stat_dyn.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/stat_rap.xml -o stat_rap.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/taal.xml -o taal.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/TankAanwezigheid.xml -o TankAanwezigheid.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/terugsaneerwaarde.xml -o terugsaneerwaarde.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/tijdelijke_maatregel.xml -o tijdelijke_maatregel.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/Toetsingen.xml -o Toetsingen.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/ToetsingVariabelen.xml -o ToetsingVariabelen.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/Toetsmeldingen.xml -o Toetsmeldingen.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/Toetsoordelen.xml -o Toetsoordelen.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/Toetsregels.xml -o Toetsregels.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/type_seb_initiatief.xml -o type_seb_initiatief.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/ubicode.xml -o ubicode.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/ubi_onderzocht.xml -o ubi_onderzocht.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/verontreinigd.xml -o verontreinigd.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/vervallen.xml -o vervallen.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/VervolgWBB.xml -o VervolgWBB.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/vervolg_in_ander_kader.xml -o vervolg_in_ander_kader.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/vervuilinggroep.xml -o vervuilinggroep.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/verzendwijze.xml -o verzendwijze.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/waterbodemkwaliteitsklasse.xml -o waterbodemkwaliteitsklasse.xml
curl https://codes.sikb.nl/0101/IMSIKB0101/zorg.xml -o zorg.xml