define(function() {
	return {
		"#preview.sikb-profiles": {
			"": "width:auto;max-width:none;margin:0;padding:0;background:#f8fafc;border:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;",
			".sikb-vcl-filter-panel": "padding:12px 28px 0 28px;background:#f8fafc;color:#111827;font-size:12px;",
			".sikb-vcl-filter-panel input": "max-width:160px;",
			".sikb-vcl-filter-panel select": "max-width:160px;",
			".sikb-vcl-filter-panel .header": "font-weight:700;margin-bottom:2px;",
			".sikb-vcl-filter-panel .{Group}": "margin:0 10px 8px 0;",
			".sikb-vcl-filter-panel .sikb-filter-root": "display:block;width:100%;border:1px solid #dbe2ea;background:white;padding:8px 10px;",
			".sikb-vcl-filter-panel .sikb-filter-root > input": "position:absolute;opacity:0;width:0;height:0;margin:0;pointer-events:none;",
			".sikb-vcl-filter-panel .sikb-filter-root > .text": "cursor:pointer;font-weight:700;",
			".sikb-vcl-filter-panel .sikb-filter-root > .text:before": "content:'\\f054';font-family:FontAwesome;margin-right:6px;color:#64748b;font-weight:400;",
			".sikb-vcl-filter-panel .sikb-filter-root.expanded > .text:before": "content:'\\f078';",
			".sikb-vcl-filter-panel .sikb-filter-root > .container": "display:none;flex-wrap:wrap;gap:8px 12px;align-items:flex-start;padding-top:8px;",
			".sikb-vcl-filter-panel .sikb-filter-root.expanded > .container": "display:flex;",
			".sikb-vcl-filter-panel .sikb-filter-toolbar": "display:flex;flex:1 0 100%;align-items:center;gap:10px;border-bottom:1px solid #e5e7eb;padding-bottom:8px;margin-bottom:4px;",
			".sikb-vcl-filter-panel .sikb-filter-stats": "color:#64748b;white-space:normal;flex:1 1 auto;",
			".sikb-vcl-filter-panel .sikb-filter-count": "color:#64748b;font-weight:700;margin-left:auto;",
			".sikb-vcl-filter-panel .fullwidth": "width:100%;max-width:none;flex:1 0 100%;",
			".sikb-vcl-filter-panel input.fullwidth": "width:100%;max-width:none;",
			".sikb-vcl-filter-panel .sikb-filter-layer-expression": "flex:1 0 100%;margin:0;",
			".sikb-vcl-filter-panel .sikb-filter-layer-expression input": "width:100%;max-width:none;",
			".sikb-vcl-filter-panel .sikb-filter-indicator-results": "display:flex;flex:1 0 100%;flex-wrap:wrap;gap:8px 18px;align-items:flex-end;max-width:100%;",
			".sikb-vcl-filter-panel .sikb-filter-indicator-results > .header": "flex:1 0 100%;",
			".sikb-vcl-filter-panel .sikb-filter-indicator-result": "margin:0;min-width:150px;max-width:220px;",
			".sikb-vcl-filter-panel .sikb-filter-indicator-result select": "width:100%;max-width:none;",
			// ".sikb-vcl-filter-panel .sikb-filter-group": "border-top:1px solid #e5e7eb;padding-top:7px;",
			".sikb-vcl-filter-panel .sikb-filter-group > .container": "display:none;flex-wrap:wrap;gap:8px;align-items:flex-end;padding-top:6px;",
			".sikb-vcl-filter-panel .sikb-filter-group.expanded > .container": "display:flex;",
			".sikb-vcl-filter-panel .sikb-filter-inline-group": "min-width:180px;",
			".sikb-vcl-filter-panel .sikb-filter-inline-group > .container": "display:none;flex-direction:column;gap:3px;padding-top:4px;",
			".sikb-vcl-filter-panel .sikb-filter-inline-group.expanded > .container": "display:flex;",
			".sikb-profile-preview": "padding:24px 28px;",
			".sikb-profile-preview-pending": "min-height:180px;",
			".sikb-profile-loading": "display:flex;flex-direction:column;gap:5px;color:#64748b;font-size:12px;",
			".sikb-profile-loading b": "color:#111827;font-size:13px;",
			".sikb-profile-summary": "display:flex;gap:14px;align-items:baseline;margin:0 0 18px 0;color:#111827;font-size:13px;",
			".sikb-profile-summary .sikb-summary-value": "color:#64748b;",
			".sikb-profile-summary .sikb-preview-separator": "color:#a0a7ad;",
			".sikb-preview-header": "position:absolute;left:0;right:0;top:0;z-index:3;box-sizing:border-box;height:44px;padding:12px 18px;overflow:hidden;white-space:nowrap;background:white;border-bottom:1px solid #dfe3e7;color:#26323c;font-size:14px;",
			".sikb-preview-header .sikb-preview-separator": "display:inline-block;margin:0 9px;color:#a0a7ad;",
			".sikb-preview-header [data-sikb-ref]": "cursor:pointer;",
			".sikb-preview-header [data-sikb-ref]:hover": "color:#1d4ed8;text-decoration:underline;",
			".sikb-preview-filters": "display:block;margin:0 0 18px 0;border:1px solid #dbe2ea;background:#fff;",
			".sikb-preview-filters summary": "display:flex;align-items:center;justify-content:space-between;gap:12px;padding:8px 10px;cursor:pointer;color:#111827;font-size:12px;font-weight:700;list-style:none;",
			".sikb-preview-filters summary::-webkit-details-marker": "display:none;",
			".sikb-preview-filters summary:before": "content:'▸';font-size:12px;color:#64748b;",
			".sikb-preview-filters[open] summary:before": "content:'▾';",
			".sikb-preview-filters summary > span:first-child": "margin-right:auto;",
			".sikb-preview-filter-body": "display:flex;flex-direction:column;gap:8px;padding:0 10px 10px 10px;border-top:1px solid #e5e7eb;",
			".sikb-preview-stats": "display:flex;flex-wrap:wrap;gap:8px;margin:10px 0 2px 0;",
			".sikb-preview-stats button": "display:flex;gap:5px;align-items:baseline;padding:4px 7px;border:1px solid #d1d5db;background:white;color:#475569;font-size:11px;cursor:pointer;",
			".sikb-preview-stats button:hover": "border-color:#94a3b8;background:#f8fafc;",
			".sikb-preview-stats b": "color:#111827;font-size:12px;",
			".sikb-filter-row": "display:flex;flex-wrap:wrap;gap:8px;align-items:flex-end;",
			".sikb-filter-row.compact": "gap:6px;",
			".sikb-filter-row label": "display:flex;flex-direction:column;gap:2px;min-width:92px;color:#64748b;font-size:10px;font-weight:600;",
			".sikb-filter-row label.wide": "min-width:190px;flex:1 1 190px;",
			".sikb-filter-row input, .sikb-filter-row select": "height:24px;padding:2px 6px;border:1px solid #cbd5e1;background:white;color:#111827;font:inherit;font-size:11px;border-radius:0;",
			".sikb-filter-row input[type='checkbox']": "height:auto;margin:0 3px 0 0;",
			".sikb-filter-row fieldset": "display:flex;flex-wrap:wrap;gap:7px;min-height:24px;align-items:center;margin:0;padding:3px 7px;border:1px solid #cbd5e1;color:#64748b;",
			".sikb-filter-row fieldset label": "display:flex;flex-direction:row;align-items:center;min-width:0;color:#111827;font-size:11px;font-weight:500;",
			".sikb-filter-row legend": "padding:0 4px;font-size:10px;font-weight:600;color:#64748b;",
			".sikb-filter-row button": "height:24px;padding:2px 9px;border:1px solid #cbd5e1;background:#f8fafc;color:#111827;font-size:11px;cursor:pointer;",
			".sikb-filter-count": "display:flex;align-items:center;color:#64748b;font-size:11px;font-weight:500;",
			".sikb-profile-grid": "display:grid;grid-template-columns:minmax(0,1fr);gap:18px;align-items:start;",
			".sikb-profile-grid.two-cols": "grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;",
			".sikb-profile-grid.single-profile": "grid-template-columns:minmax(0,1fr);gap:18px;",
			".sikb-profile-sentinel": "display:flex;justify-content:center;align-items:center;min-height:42px;margin:14px 0;color:#64748b;font-size:12px;",
			".sikb-profile-sentinel:empty": "display:none;",
			".sikb-profile-sentinel button": "height:28px;padding:4px 12px;border:1px solid #cbd5e1;background:white;color:#111827;font-size:12px;cursor:pointer;",
			".sikb-profile-sentinel button:hover": "border-color:#94a3b8;background:#f8fafc;",
			".sikb-profile-card": "background:white;border:1px solid #d1d5db;box-shadow:0 1px 2px rgba(15,23,42,0.08);",
				".sikb-profile-card.filtered-out": "display:none;",
				".sikb-profile-defs": "position:absolute;width:0;height:0;overflow:hidden;",
				".sikb-profile-layout": "position:absolute;left:0;right:0;top:44px;bottom:0;overflow:hidden;width:auto;height:auto;background:white;",
				".sikb-profile-zoom-viewport": "position:absolute;left:0;right:0;top:0;bottom:39px;overflow:hidden;width:auto;height:auto;background:white;touch-action:none;overscroll-behavior:contain;cursor:grab;",
				".sikb-profile-zoom-viewport.dragging": "cursor:grabbing;",
				".sikb-profile-zoom-content": "position:relative;display:inline-block;min-width:100%;transform-origin:0 0;will-change:transform;",
				".sikb-profile-legend": "position:absolute;left:0;right:0;bottom:0;box-sizing:border-box;display:flex;align-items:center;gap:17px;height:39px;padding:8px 18px;overflow-x:auto;overflow-y:hidden;white-space:nowrap;background:white;border-top:1px solid #dfe3e7;color:#57636c;font-size:11px;z-index:2;",
				".sikb-legend-item": "display:inline-flex;align-items:center;gap:5px;",
				".sikb-legend-item i": "display:inline-block;box-sizing:border-box;width:11px;height:11px;border:1px solid rgba(15,23,42,.45);flex:0 0 auto;",
				".sikb-legend-sand": "background-color:#fed967;background-image:radial-gradient(#111827 18%,transparent 20%);background-size:4px 4px;",
				".sikb-legend-gravel": "background-color:#f9803e;background-image:radial-gradient(transparent 28%,#111827 31%,#111827 40%,transparent 43%);background-size:6px 6px;",
				".sikb-legend-clay": "background-color:#a8cd91;background-image:repeating-linear-gradient(135deg,transparent 0,transparent 3px,#111827 3px,#111827 4px);",
				".sikb-legend-silt": "background-color:#a6a6a6;background-image:repeating-linear-gradient(90deg,transparent 0,transparent 3px,#111827 3px,#111827 4px);",
				".sikb-legend-peat": "background-color:#843c09;background-image:repeating-linear-gradient(0deg,transparent 0,transparent 4px,#111827 4px,#111827 5px);",
				".sikb-legend-filter": "background:#67c2a3;border-style:dashed;",
				".sikb-legend-finishing": "background:#b8b8b8;",
				".sikb-legend-sample": "background:#fff;border-color:#111827;",
				".sikb-legend-norm": "margin-left:auto;padding-left:8px;color:#475569;",
				".sikb-legend-norm b": "color:#26323c;",
				".sikb-sample-testing-report": "display:flex;flex-direction:column;gap:16px;",
				".sample-testing-facts": "padding:0;border-top:0;",
				"svg.sikb-sample-testing-svg": "width:100%;max-width:760px;height:auto;background:white;border:1px solid #d1d5db;display:block;",
				".sample-testing-title": "font-size:15px;font-weight:700;fill:#111827;",
				".sample-testing-label": "font-size:11px;font-weight:600;fill:#111827;text-anchor:end;",
				".sample-testing-count": "font-size:11px;font-weight:700;fill:#111827;",
				".sample-testing-empty": "font-size:12px;fill:#64748b;",
				".sample-testing-axis": "stroke:#94a3b8;stroke-width:0.8;",
				".sample-testing-bar": "stroke:#111827;stroke-width:0.4;fill-opacity:0.88;",
				".sikb-sample-testing-table": "width:100%;table-layout:fixed;border-collapse:collapse;background:white;border:1px solid #d1d5db;font-size:12px;color:#111827;",
				".sikb-sample-testing-table col.sample-testing-col-testing": "width:6%;",
				".sikb-sample-testing-table col.sample-testing-col-sample": "width:8%;",
				".sikb-sample-testing-table col.sample-testing-col-badges": "width:12%;",
				".sikb-sample-testing-table col.sample-testing-col-measurement": "width:7%;",
				".sikb-sample-testing-table col.sample-testing-col-depth": "width:7%;",
				".sikb-sample-testing-table col.sample-testing-col-observation": "width:21%;",
				".sikb-sample-testing-table col.sample-testing-col-package": "width:11%;",
				".sikb-sample-testing-table col.sample-testing-col-matrix": "width:8%;",
				".sikb-sample-testing-table col.sample-testing-col-date": "width:9%;",
				".sikb-sample-testing-table col.sample-testing-col-analysis": "width:7%;",
				".sikb-sample-testing-table col.sample-testing-col-message": "width:4%;",
				".sikb-sample-testing-table th, .sikb-sample-testing-table td": "vertical-align:top;text-align:left;border-bottom:1px solid #e5e7eb;padding:8px 9px;overflow-wrap:anywhere;",
				".sikb-sample-testing-table tr.filtered-out": "display:none;",
				".sikb-sample-testing-report:not(.show-zero-toetsoordelen) .sikb-sample-testing-table tr.sample-testing-zero-only": "display:none;",
				".sikb-sample-testing-table thead th": "position:sticky;top:0;background:#f8fafc;color:#475569;font-size:11px;font-weight:700;z-index:1;",
				".sikb-sample-testing-table tbody th": "font-weight:700;min-width:120px;",
				".sikb-sample-testing-table button": "appearance:none;border:0;background:transparent;padding:0;color:#111827;font:inherit;font-weight:700;text-align:left;",
				".sikb-sample-testing-table ul": "margin:0;padding-left:14px;",
				".sikb-sample-testing-table li": "margin:0 0 3px 0;",
				".sikb-sample-testing-table li span": "display:block;color:#111827;",
				".sikb-sample-testing-table li b": "display:block;color:#64748b;font-weight:500;",
				".sample-testing-badges": "display:flex;flex-wrap:wrap;align-items:flex-start;gap:4px;",
				".sample-testing-chip": "display:inline-flex;align-items:center;gap:5px;margin:0;max-width:100%;padding:2px 5px;border:1px solid rgba(15,23,42,0.55);border-radius:5px;color:#111827;font-size:11px;font-weight:700;line-height:1.2;",
				".sample-testing-chip span": "display:inline-flex;align-items:center;justify-content:center;min-width:14px;height:14px;padding:0 3px;border-radius:7px;background:rgba(255,255,255,0.72);font-size:9px;font-weight:700;",
				".sikb-sample-testing-report:not(.show-zero-toetsoordelen) .sample-testing-zero": "display:none;",
				".sample-testing-value": "display:inline-block;max-width:100%;margin:0 4px 4px 0;padding:2px 5px;border:1px solid #dbe2ea;background:#f8fafc;color:#111827;font-size:11px;line-height:1.25;",
				".sample-testing-details summary": "cursor:pointer;color:#334155;font-weight:700;white-space:nowrap;",
				".sample-testing-details[open] summary": "margin-bottom:5px;",
				".sample-testing-details > div": "display:flex;flex-wrap:wrap;gap:0;",
				".sample-testing-time .sample-testing-value": "white-space:normal;overflow-wrap:normal;",
				".sample-testing-date": "white-space:nowrap;",
				".sample-testing-clock": "display:inline-block;white-space:nowrap;",
				".sample-testing-testing .sample-testing-value": "white-space:nowrap;",
				".sample-testing-observations": "font-size:11px;line-height:1.28;",
				".sample-testing-analysis ul": "max-height:210px;overflow:auto;padding-right:4px;",
				".sample-testing-muted": "color:#64748b;",
				"svg.sikb-borehole-profile": "width:100%;height:auto;background:white;display:block;",
				".sikb-profile-facts": "display:flex;flex-wrap:wrap;gap:8px;padding:8px 10px;border-top:1px solid #e5e7eb;color:#64748b;font-size:11px;",
				".sikb-profile-facts b": "color:#111827;",
				".profile-title": "font-size:18px;font-weight:700;fill:#111827;text-anchor:middle;",
				".profile-axis": "stroke:#111827;stroke-width:1;",
				".profile-axis-title": "font-size:9px;font-weight:700;fill:#111827;text-anchor:end;",
				".profile-tick": "stroke:#111827;stroke-width:0.6;",
				".profile-tick.major": "stroke-width:1;",
					".profile-depth-label": "font-size:8px;fill:#111827;text-anchor:end;",
					".profile-hole": "fill:white;stroke:#111827;stroke-width:1.2;",
					".profile-hole-gap": "fill:transparent;stroke:transparent;stroke-width:1.2;",
					".profile-layer-fill": "stroke:none;",
				".profile-layer-line": "stroke:#111827;stroke-width:0.9;",
				".profile-finishing": "stroke:#111827;stroke-width:0.6;fill-opacity:0.86;",
				".profile-filter-name": "font-size:8px;font-weight:700;fill:#111827;text-anchor:middle;",
				".profile-filter-depth": "font-size:8px;fill:#111827;text-anchor:end;",
				".profile-filter-pipe": "fill:#8d8d8d;stroke:none;",
				".profile-filter-screen": "fill:#4395d1;stroke:#111827;stroke-width:0.75;stroke-dasharray:3 2;",
				".profile-filter-dash": "stroke:#111827;stroke-width:0.7;stroke-dasharray:3 2;",
				".profile-sample": "fill:white;stroke:#111827;stroke-width:0.8;",
				".profile-sample-label": "font-size:8px;fill:#111827;text-anchor:middle;",
				".profile-leader": "stroke:#111827;stroke-width:0.6;fill:none;",
					".profile-description": "font-size:8.5px;font-weight:600;fill:#111827;",
					".profile-right-depth": "font-size:8px;fill:#111827;text-anchor:start;",
					".profile-detail-label": "font-size:8px;font-weight:700;fill:#111827;text-anchor:end;",
					".profile-detail-value": "font-size:8px;font-weight:700;fill:#111827;",
							".profile-clickable": "cursor:pointer;",
							".profile-clickable:hover": "color:#1d4ed8;fill:#1d4ed8;text-decoration:underline;",
							".profile-clickable-shape": "cursor:pointer;vector-effect:non-scaling-stroke;pointer-events:all;",
						".profile-clickable-shape:hover": "stroke:#1d4ed8;stroke-width:2;filter:drop-shadow(0 0 2px rgba(29,78,216,0.45));"
					}
	};
});
